#!/bin/bash

magoo_apha=255
export magoo_line=AAFFDD0E
export magoo_levels=2

export magoo_range01=000000-444444
export magoo_color01=88FFFF00
export magoo_range02=BBBBBB-FFFFFF
export magoo_color02=880000FF

magoo $@


